### ISSUE TITLE
Issue 12: Add a "README.md" file for "In-Browser Execution for Compiler Explorer" project (CE frontend)

### ISSUE THREAD

**Issue by geniuseva** [maemre/compiler-explorer#16]
The new version of "README.md" file will include information about adding Cflat language, adding Cflat compiler, how to compile it from Wasm instead of CE server, how to add another compiler, how to run different passes of a chosen compiler. Also, the build process, test run, and what to expect when running it.

**Comment by arbie333** [comment]
@maemre Can we add our readme file (as shown below) to this repo?

# Project: In-browser Execution for Compiler Explorer
## Information about the project
### What is compiler explorer?
Compiler Explorer is an interactive compiler exploration website. Edit code in C, C++, C#, F#, Rust, Go, D, Haskell, Swift, Pascal, ispc, Python, Java, or any of the other 30+ supported languages, and see how that code looks after being compiled in real time. Multiple compilers are supported for each language, many different tools and visualizations are available, and the UI layout is configurable (thanks to GoldenLayout).

### What is our project about?
This project focuses on enhancing Compiler Explorer (CE) by adapting it to support in-browser compilers. The primary objectives include restructuring the backend by removing the original CE server and integrating WebAssembly (Wasm) code for compiler execution. Additionally, the project aims to add a new feature of running different compiler passes so that users can better understand the compiler process. Furthermore, the project implements another functionality to load different compilers.

## Build process
### Installing Prerequisites
```bash=
pip install node
node --version
v18.16.0

pip install npm
npm --version
9.5.1
```

### Generate "cflat.js" from farrago repo
- Follow the steps in ["README.md"](https://github.com/maemre/farrago/blob/master/cflat/README.md)



### Running the developer version of this program
```bash
# go to the right directory
cd compiler-explorer/

# run the developer version
make dev EXTRA_ARGS="--language cflat"

```

### What to expect?
- Wait until the terminal shows the following lines.
```
info:   Listening on http://localhost:10240/
info:   Startup duration: 13769ms
info: =======================================
```
- Open the [local webpage](http://localhost:10240/) in any browser
- See the wepage like this
<img width="1595" alt="Screenshot 2023-08-03 at 18 04 37" src="https://github.com/maemre/compiler-explorer/assets/97008773/117e374a-b61b-4a37-92b3-283a048efd75">

- If you see `<Compilation failed: unreachable>` on the right hand side (as shown below), try to add a new line at the very end of your input codes on the left hand window.
<img width="1600" alt="Screenshot 2023-08-03 at 18 05 52" src="https://github.com/maemre/compiler-explorer/assets/97008773/f36b16da-57a5-4457-9e13-796a248de3a0">


## Test

### Run the test
```bash=
make test
```
### What to expect?
The terminal is going to run more than 520 tests, and Cflat compiler contains 2 tests among them. If you find them paased as shown below, you are good to go.
```bash=
...
# The cflat part
  Basic compiler setup
    ✔ Should not crash on instantiation

  cflatp compiling
    ✔ Compiles a simple LIR program
...
```

**Comment by maemre** [comment]
The repo contains substantially more than your 590 project. You should add the documentation relevant to your project as a `.md` file under the `docs/` directory. Create a new PR for that file. Overall, the content in the `What is compiler explorer?` section isn't necessary if this is under `docs/`.

You can edit README.md to add a link to your project's description.

**Comment by geniuseva** [comment]
Thanks for the suggestions! I have made changes and opened a new pull request. Please review it to see if it makes sense now.
