### ISSUE TITLE
Issue 2: Add the Cflat Compiler to Compiler-explorer

### ISSUE THREAD

**Issue by geniuseva** [maemre/compiler-explorer#2]
Final version will be that users can run Cflat compiler on compiler explorer (CE) on local machines.

**Comment by geniuseva** [comment]
@maemre We still need help! We don't know how to shuffle the arguments around to give the compiler binary exactly two arguments: the input file and the output file in that order.

**Comment by maemre** [comment]
I'm not available to meet until next Wednesday (except our weekly meeting), so we need to figure things out over GitHub issues. Please describe:

- What have you tried?
- What errors are you getting on the server-side logging console? What error is the `lirc` binary giving?
- What are the arguments you're passing to the compiler?
  - You will probably need to override the exec or runCompiler methods in your compiler class to add logging to see this. The one from the C3 compiler doesn't work because it expects different arguments.
- Where are the input and output file locations, does the input file have the right contents?

Then, we can figure out how you can shuffle the arguments around to give the compiler binary exactly two arguments: the input file and the output file in that order.

Also, the documentation for adding a new compiler mentions how to get the output file name, that may be handy. Try calling it and log & inspect its output.

**Comment by geniuseva** [comment]
“Also, the documentation for adding a new compiler mentions how to get the output file name, that may be handy. Try calling it and log & inspect its output.” -> We can get the output file name as string now, we tried inserting some “console.log” in BaseCompiler, and figured out the way to get it.

**Comment by geniuseva** [comment]
“What errors are you getting on the server-side logging console? What error is the lirc binary giving?” -> The error we are getting is that the correct usage of the lirc command was not followed.

**Comment by geniuseva** [comment]
“What are the arguments you're passing to the compiler?” ->
The expected argument should look like below:
/Users/yinhu2/Desktop/farrago/target/debug/lirc [lir-file] [output-file]

But now, we can only pass something like below:
/Users/yinhu2/Desktop/farrago/target/debug/lirc [output-file] [lir-file]

We are unable to inverse the order of output-file and lir-file.

**Comment by arbie333** [comment]
“Where are the input and output file locations, does the input file have the right contents?” ->

Input file location: 
/var/folders/87/cd_m04yx2nqfk8k9ljzt2xc80000gn/T/compiler-explorer-compiler2023530-21393-1k9l64d.5g6bk/

Output file location: /var/folders/87/cd_m04yx2nqfk8k9ljzt2xc80000gn/T/compiler-explorer-compiler2023530-21393-1k9l64d.5g6bk/

This is the result after we ran ”make dev EXTRA_ARGS="--debug --language cflat"”.
![image](https://github.com/maemre/compiler-explorer/assets/50132979/09df356b-4699-4a1e-92f0-4fbda3e07d30)

**Comment by arbie333** [comment]
“What have you tried?” -> We have tried to modify cflat.ts (as shown below). After we added some “console.log”, we found out that the compiler was called correctly, but the order of the calling command is incorrect. We need to shuffle the arguments around to give the compiler binary exactly two arguments: the input file and the output file in that order. We tried to override the OptionForFilters()/ optionsForBackend() because it returns the output file dir first, and then the input file dir. So, we tracked back functions and found out where the order was made: prepareArugments() and orderArguments() also as the screenshot shown below. But we don’t think those are something we should override. 
![image](https://github.com/maemre/compiler-explorer/assets/50132979/6b58be69-a745-4c95-a9e9-aab783f86850)
![image](https://github.com/maemre/compiler-explorer/assets/50132979/a54ac0bf-359e-4ce2-b919-f90006866aab)

**Comment by geniuseva** [comment]
Also, we are unable to push this "cflat.ts" version to this branch due to some technical issue.

**Comment by maemre** [comment]
This is really helpful.

Also, don't screenshot code in issues (it's text, not image, and it has
issues around accessibility, people using email-based flows, etc.). Link to
the relevant code and put it relevant bits as a code block instead.

You can override prepareArguments to give the input file as the first
option. I think overriding it makes sense (it's where you specify an order
of arguments for this particular compiler).

What's the technical issue you are having when trying to add cflat.ts?

**Comment by geniuseva** [comment]
I have solved the previous issue, but now there is a new error.

As shown below, I have passed correct arguments to the command, but then it said that it was expecting to find a local_ident but found a "}" instead. But my input lir file's content is as same as the "branch.lir" file, so I don't know why and how to fix it. @maemre 
 
debug: Execution {"args":["/Users/yinhu2/Desktop/compiler-explorer/examples/lir/default.lir","/Users/yinhu2/Desktop/compiler-explorer/examples/lir/output.asm"],"command":"/Users/yinhu2/Desktop/farrago/target/debug/lirc","result":{"code":101,"execTime":"13","okToCache":true,"stderr":"thread 'main' panicked at 'Syntax error:   --> 14:1\n   |\n14 | }\n   | ^---\n   |\n   = expected local_ident', cflat/src/bin/lirc.rs:27:27\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n","stdout":"","timedOut":false},"type":"executed"}
<img width="1593" alt="Screenshot 2023-07-04 at 23 46 30" src="https://github.com/maemre/compiler-explorer/assets/97008773/a6f80f0d-d231-4c00-b180-1fdf00f5e22c">

**Comment by maemre** [comment]
Can you try adding a new line at the end? lir files need to end with a new
line.

**Comment by geniuseva** [comment]
Problem solved! Thanks!
